# -*- coding: utf-8 -*-
"""mulesoft task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uXQZw87A4lVZQBvh1oRL1RpJpSn6pJoi
"""

import sqlite3

# conn = sqlite3.connect(':memory:')
conn = sqlite3.connect('movies.db')

# create a cursor
cur = conn.cursor()

#create a table
cur.execute("""CREATE TABLE moviedetails(
        movie_name text,
        actor_name text,
        actress_name text,
        release_year text,
        director_name
    )""")

many_records = [
    ('Shershaah', 'Sidharth', 'Kiara', '2021', 'Vishnuvardhan'),
     ('Atarngi Re', 'Dhanush', 'Sara', '2022', 'Anand L.Rai'),
     ('Sanak', 'Vidhyut', 'Rukmini', '2021', 'Kanishk Varma'),
]
cur.executemany("INSERT INTO moviedetails VALUES (?,?,?,?,?)", many_records)

# insert only one record into details table
cur.execute("INSERT INTO  moviedetails VALUES ('Bhuj', 'Ajay', 'Nora', '2021', 'Abhihek Dudhaiya')")

#  Update records into the details table 
# cur.execute("""UPDATE details SET release_year='1 October 2002'
#     WHERE rowid = 1
#     """)

# Delete record from the details table 
# cur.execute("DELETE from details WHERE rowid=4")

# Drop details table
# cur.execute("DROP TABLE details")

# Query The Database

cur.execute("SELECT rowid, * FROM moviedetails")

# print(cur.fetchone())
# print(cur.fetchmany(3))

# fetch and print all records of the table
items = cur.fetchall()
# print(items)

for item in items:
    print(item)

# commit our command
conn.commit()

# close our connection
conn.close()